#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD_ID_FILE = ROOT / "BUILD_ID"
BUNDLE_PATH = ROOT / "runtime.bundle.js"
INDEX_PATH = ROOT / "index.html"

SOURCES = [
    "vendor/qrcode.min.js",
    "pongbot-protocol.js",
    "pongbot-ble.js",
    "robot-geometry.js",
    "launch-model.js",
    "guided-calibration.js",
    "drill-adjustments.js",
    "shot-variation.js",
    "protocol-debug.js",
    "studio-features-core.js",
    "debug-advisor.js",
    "app.js",
    "studio-features.js",
]


def build_id() -> str:
    value = BUILD_ID_FILE.read_text(encoding="utf-8").strip()
    if not value or not re.fullmatch(r"[A-Za-z0-9._-]+", value):
        raise SystemExit("BUILD_ID must contain only letters, digits, dot, underscore, or hyphen")
    return value


def render_bundle() -> str:
    bid = build_id()
    parts = [
        "/* Table Tennis Robot Studio generated runtime bundle.\n"
        f" * Build: {bid}\n"
        " * Generated by scripts/build_runtime_bundle.py. Do not edit this file directly.\n"
        " * QRCode third-party license: vendor/QRCode-LICENSE.txt and THIRD_PARTY_NOTICES.md\n"
        " */\n",
        f"globalThis.__TTRS_BUILD_ID = {bid!r};\n",
    ]
    for rel in SOURCES:
        path = ROOT / rel
        if not path.is_file():
            raise SystemExit(f"Missing runtime source: {rel}")
        text = path.read_text(encoding="utf-8")
        parts.append(f"\n/* ===== BEGIN {rel} ===== */\n")
        parts.append(text)
        if not text.endswith("\n"):
            parts.append("\n")
        parts.append(f"/* ===== END {rel} ===== */\n")
    return "".join(parts)


def updated_index_text() -> str:
    html = INDEX_PATH.read_text(encoding="utf-8")
    bid = build_id()
    start = html.find('  <script src="pongbot-protocol.js"></script>')
    end_token = '  <script src="studio-features.js"></script>'
    end = html.find(end_token)
    replacement = f'''  <script src="runtime.bundle.js?v={bid}" onerror="globalThis.__TTRS_BUNDLE_LOAD_ERROR = true"></script>\n  <script>\n    (() => {{\n      if (globalThis.__TTRS_BUNDLE_LOAD_ERROR) {{\n        const banner = document.createElement("div");\n        banner.className = "fatal-banner";\n        banner.textContent = "Table Tennis Robot Studio could not load its runtime file. This GitHub Pages deployment is incomplete or mixed between releases. Upload/commit the whole repository release together, then reload.";\n        document.body.appendChild(banner);\n      }} else if (!globalThis.__TTRS_BOOT_OK && !globalThis.__TTRS_BOOT_ERROR) {{\n        const banner = document.createElement("div");\n        banner.className = "fatal-banner";\n        banner.textContent = "Table Tennis Robot Studio did not finish starting. Reload once; if it persists, deploy the complete release rather than individual files.";\n        document.body.appendChild(banner);\n      }}\n    }})();\n  </script>'''
    if start < 0 or end < 0:
        # Already bundled: only refresh the build query string.
        pattern = r'<script src="runtime\.bundle\.js\?v=[^"]+" onerror="globalThis\.__TTRS_BUNDLE_LOAD_ERROR = true"></script>'
        new, count = re.subn(pattern, f'<script src="runtime.bundle.js?v={bid}" onerror="globalThis.__TTRS_BUNDLE_LOAD_ERROR = true"></script>', html, count=1)
        if count != 1:
            raise SystemExit("Could not find either the source script block or runtime.bundle.js tag in index.html")
        return new
    end += len(end_token)
    return html[:start] + replacement + html[end:]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated bundle/index are stale")
    args = parser.parse_args()

    expected_bundle = render_bundle()
    expected_index = updated_index_text()

    if args.check:
        problems = []
        if not BUNDLE_PATH.is_file() or BUNDLE_PATH.read_text(encoding="utf-8") != expected_bundle:
            problems.append("runtime.bundle.js is missing or stale")
        if INDEX_PATH.read_text(encoding="utf-8") != expected_index:
            problems.append("index.html runtime bundle reference is stale")
        if problems:
            raise SystemExit("; ".join(problems) + ". Run: python3 scripts/build_runtime_bundle.py")
        print(f"Runtime bundle check: PASS ({build_id()})")
        return

    BUNDLE_PATH.write_text(expected_bundle, encoding="utf-8")
    INDEX_PATH.write_text(expected_index, encoding="utf-8")
    print(f"Built {BUNDLE_PATH.name} for {build_id()} from {len(SOURCES)} source files")


if __name__ == "__main__":
    main()
